#!/usr/bin/env bash

get_volume_status() {
	local volume_status
	volume_status=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)

	local volume
	local is_muted
	volume=$(echo "$volume_status" | awk '{print int($2 * 100)}')
	if echo "$volume_status" | grep -q "[MUTED]"; then
		is_muted=true
	else
		is_muted=false
	fi

	echo "${volume} ${is_muted}"
}

volume_notification() {
	local volume_status
	volume_status=$(get_volume_status)

	local volume
	volume=$(echo "$volume_status" | awk '{print $1}')

	local is_muted
	is_muted=$(echo "$volume_status" | awk '{print $2}')

	# TODO: use real icons instead of of text-based ones
	# use dunstify -i <icon-name> (audio-volume-muted-symbolic,
	# audio-volume-low-symbolic, audio-volume-medium-symbolic,
	# audio-volume-high-symbolic)
	#
	# The current issue is that color of these icons does not match with the theme
	# of the rest of the system.
	# I can copy the icons (from e.g. Papirus icon set) and create "custom" icons
	# in .local/share/icons/TokyoNight that would match the color of the rest of
	# the system, but it would be another maintenance burden
	# Setting icon_theme = "TokyoNight, Papirus" in dunst config would than make
	# dunst to use my custom icons, or fallback to papirus.
	#
	# TODO: maybe different notification daemons can recolor the icons? Investigate
	# this possibility as well.
	local pseudo_icon
      "default": ["", " ", " "]
	if [ "$is_muted" = "true" ] || [ "$volume" -eq 0 ]; then
		pseudo_icon=" "
	elif [ "$volume" -le 33 ]; then
		pseudo_icon=""
	elif [ "$volume" -le 66 ]; then
		pseudo_icon=" "
	else
		pseudo_icon=" "
	fi
	dunstify \
		-h string:x-canonical-private-synchronous:audio \
		"Volume $pseudo_icon [${volume}%]" \
		-h int:value:"${volume}"
}

inc_volume() {
	wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+ && volume_notification
}

dec_volume() {
	wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && volume_notification
}

toggle-mute() {
	wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle && volume_notification
}

# main
case "${1:-}" in
	--inc)
		inc_volume
		;;
	--dec)
		dec_volume
		;;
	--toggle-mute)
		toggle-mute
		;;
	--get|"")
		get_volume_status
		;;
	*)
		echo "Usage: $0 [--inc|--dec|--toggle-mute|--get]" >&2
		exit 1
		;;
esac
